name: dart_app_use_package
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

publish_to: none

# Add regular dependencies here.
dependencies:
  dart_library_test:
    git:
      url: https://github.com/FarellAlva/dart_library_test.git
      path: dart_library_test 
      ref: 1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
